### PR TITLE
WIP: Update submodules for 0.8.0

### PR DESCRIPTION
**Pull request by TomAugspurger**
0.8.0 isn't final yet, but I wanted to test and see if we need any changes for this build to work.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@matthew-brett is this repository setup for upload artifacts to wheels.scipy.org? I notice [in the output](https://travis-ci.org/MacPython/statsmodels-wheels/jobs/199314605#L614)

> WARNING: secret API key missing: skipping package upload

**Comment by matthew-brett** [comment]
@TomAugspurger - I think you'll find that the missing key is just because the upload isn't enabled for pull requests.  Once merged, this should upload.  Is it ready to merge?

I've added you as a collaborator to this repo, so feel free to work in the main branch directly.

**Comment by TomAugspurger** [comment]
Thanks, makes sense. This should be close, just need to tag the final commit, and then I'll trigger the build.

**Comment by TomAugspurger** [comment]
Hi @matthew-brett, https://travis-ci.org/MacPython/statsmodels-wheels/jobs/199672829#L780 has the build for master. Should I be concerned that the same warning about the key not being there?

I can debug this later, but I'm not really sure where to start.

**Comment by matthew-brett** [comment]
Ah - sorry - maybe that was not the correct encrypted key.  I've rerun the encryption and added it  - let's see if the upload works now.

**Pull request merged**
