### PR TITLE
Upload nighlighties to new location

### PR DESCRIPTION
**Pull request by jarrodmillman**
Update to use new location for nightly builds:

    https://anaconda.org/scientific-python-nightly-wheels/

More details are available here:

    https://scientific-python.org/specs/spec-0004/

Also see https://github.com/statsmodels/statsmodels/pull/8899

### CODE REVIEW

**Comment by bashtage** [comment]
Thanks.  It will fail until we get the package created and a token, but at least it is pointing in the right direction.

**Comment by tupui** [comment]
Hi @bashtage,

To move forward I need the following:

1. Tell us who needs to be responsible for nighlies for your package. And give us the anaconda handles.
2. We download from PyPi a wheel and upload it using an admin token (feel free to provide a link if you want something specific, ideally you would upload yourself something "more substantial" if needed shortly after so it should not really matter much). This will create the package. We link the package to your group.
3. You can now create a personal token and upload your package.

Let me know if you need any assistance, I am happy to make calls to speed up things or we can chat on Slack/Discord.

**Comment by bashtage** [comment]
Hi @tupui , probably just me, although you could also add @josef-pkt for safety and continuity. My anaconda is also bashtage . Would be also good to add the "corporate" account, handle statsmodels.

* bashtage
* statsmodels

**Comment by tupui** [comment]
All done:

https://anaconda.org/scientific-python-nightly-wheels/statsmodels

I added the 3 accounts.

You should now be able to use a personal token to administrate the package. Let me/us know if there are any issues. Moving forward, for transparency please make an issue on https://github.com/scientific-python/specs

**Comment by bashtage** [comment]
Hi @tupui 

I was trying to set things up, and I think I need to make an upload key.  However, I don't see scientific-python-nightly-wheels as an organization.  Should I see this?

**Comment by tupui** [comment]
@bashtage this is expected, you should only see a new `Settings` tab if you go to https://anaconda.org/scientific-python-nightly-wheels/statsmodels

To create a personal token, you need to go to your settings then Access. Use the following `Allow write access to the API site` and `Allow uploads to Standard Python repositories`. You might need `Allow read access to the API site` if you want to play more with the token locally, but not required for the CI itself.

**Pull request merged**
