### PR TITLE
ENH: Add anaconda.org upload

### PR DESCRIPTION
**Pull request by bashtage**

### CODE REVIEW

**Comment by mattip** [comment]
Ahh, cool! Once this works I can copy it for NumPy :) Did you need to do anything special with secrets?

**Comment by bashtage** [comment]
I just copied the same that we have been using for the multibuild-based version.  The only thing that I think needs to be done is to redirect them to the GITHUB_ENV , e.g., so that they can be used later.

```
echo "TOKEN=$MULTIBUILD_WHEELS_STAGING_ACCESS" >> $GITHUB_ENV
```

**Comment by mattip** [comment]
The merged CI is [failing](https://github.com/MacPython/statsmodels-wheels/runs/4717471404?check_suite_focus=true) with "ls: cannot access './wheelhouse/*.whl': No such file or directory"

**Comment by bashtage** [comment]
I had a small typo above where I used ../wheelhouse instead of just wheelhouse.  That code couldn't run until merged so hard to spot.

**Comment by mattip** [comment]
Nice. I wonder why some of the wheeels (it seems the `manylinux_2_17_x86_64.manylinux2014_x86_64` ones?) doubled in size

https://anaconda.org/multibuild-wheels-staging/statsmodels/files

**Comment by bashtage** [comment]
Looks like cibuildwheel doesn't strip strings. Running `strip -g` on single .so file reduced it from 1.3MiB to around 250kiB.

**Comment by bashtage** [comment]
Might need to manually specify something like

https://github.com/multi-build/multibuild/blob/b89bb903e94308be79abefa4f436bf123ebb1313/configure_build.sh#L40-L48

**Comment by bashtage** [comment]
See pypa/cibuildwheel#331

**Comment by bashtage** [comment]
@mattip Much better now https://anaconda.org/multibuild-wheels-staging/statsmodels/files

**Pull request merged**
