### PR TITLE
Add frontend to CIBW

### PR DESCRIPTION
**Pull request by bashtage**

### CODE REVIEW

**Comment by henryiii** [comment]
I'm expecting best way to debug this will be a local run.

**Comment by henryiii** [comment]
Yep, running this:

```console
$ git checkout rel-0.13.0
$ git submodule update --init --recursive
$ pipx run cibuildwheel --platform linux --print-build-identifiers statsmodels/
cp38-manylinux_x86_64
cp39-manylinux_x86_64
cp310-manylinux_x86_64
cp38-manylinux_i686
cp39-manylinux_i686
cp310-manylinux_i686
pp38-manylinux_x86_64
pp38-manylinux_i686
cp38-musllinux_x86_64
cp39-musllinux_x86_64
cp310-musllinux_x86_64
cp38-musllinux_i686
cp39-musllinux_i686
cp310-musllinux_i686
```

And looking in setup.py, I see this:

```python
  python_requires=">=3.8",
```

I think you have the wrong commit in the submodule.

I wonder if we can make the Python requires setting a bit more obvious.

Also, I'd personally make a cibuildwheel.toml file, put all configuration in that, then use `--config-file=cibuildwheel.toml`, would make local runs easier.

**Comment by bashtage** [comment]
@henryiii it is a bti tricky. 

If you look [at the github actions workflow](https://github.com/MacPython/statsmodels-wheels/blob/rel-0.13.0/.github/workflows/build-wheels.yml), there is a command

```
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse statsmodels
        env:
          CIBW_BEFORE_BUILD: 'git submodule foreach git checkout  ${{ env.BUILD_COMMIT }}'
```

where `BUILD_COMMIT` is v0.13.2.

So it is indeed building 0.13.2

If you take a look at https://github.com/MacPython/statsmodels-wheels/runs/5117466980?check_suite_focus=true which is the successful run for 3.8, you'll see that it indeed build 0.13.2 (e.g., `Successfully built statsmodels-0.13.2-cp38-cp38-linux_x86_64.whl`).

Something is crashing silently somewhere but it is really not obvious what it is.

**Comment by bashtage** [comment]
You need to change your submodule command to

```
git submodule foreach git checkout v0.13.2
```

**Comment by bashtage** [comment]
FWIW if you know a better way to build a branch that isn't main, or a specific commit, I'm very happy to change how I am doing this.

**Comment by henryiii** [comment]
> it is starting the build before it runs the command

No, it's not starting the build, it's just running the configuration, and it's picking up the current submodule. It has to configure before it knows what to build.

> FWIW if you know a better way to build a branch that isn't main, or a specific commit

Why can't you just checkout `v0.13.2` as a git submodule? Git stores the submodule commit - you can just update it to `v0.13.3`, etc, just like you'd update this line in a GHA file. There are two other options.

You can tell git to follow the tip of a remove branch with `git submodule add -b` rather than a locked commit. Ugly, IMO, since you are trying to build a specific commit anyway (`v0.13.2`), so that should be locked into the git repo, but can be done, I believe.

The other possibility is to set `CIBW_PROJECT_REQUIRES_PYTHON`, which will override the search for `python_requires` in the `setup.py`. You might run into other weird quirks having the latest main checked out during configure, though I don't know of any others currently; this will fix your immediate problem.

**Comment by henryiii** [comment]
If you follow my suggestion and place cibuildwheel config in a `cibuildwheel.toml` file, then this setting is `[project] requires-python = ">=3.7"`, following PEP 621, FYI.

**Comment by bashtage** [comment]
> Why can't you just checkout v0.13.2 as a git submodule? Git stores the submodule commit - you can just update it to v0.13.3, etc, just like you'd update this line in a GHA file. Yes, it's a specific commit, but so is git submodule foreach git checkout v0.13.2. There are two other options.

I could but this breaks the simplicity of our release flow since now there are two things to change. I've found a way to make a dummy commit dynamically that will run and preserve the branch change so that cibuildwheel will pick up the correct branch.  Likely fix in #117  

> The other possibility is to set CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7", which will override the search for python_requires in the setup.py. You might run into other weird quirks having the latest main checked out during configure, though I don't know of any others currently; this will fix your immediate problem.

This might be simplest since we only ever ask for builds that are supported.  I could just leave this at 3.7 irrespective of the actual.

Thanks for the help.

**Pull request closed without merging**
